### ISSUE TITLE
Direct Peering Sessions by Router via API broken

### ISSUE THREAD

**Issue by mngan** [peering-manager/peering-manager#530]
### Peering Manager version

v1.5.2

### Python version

3.8

### Steps to Reproduce

Using the script below, I would expect this to work, which it did back in v1.3.2

```
import pypeeringmanager as pypm
from devtools import debug

api = pypm.api(url="http://localhost:8080", token="0123456789abcdef0123456789abcdef01234567")
r = api.peering.routers.get(name='bg1-ams1')
debug(r.serialize())

s = api.peering.direct_peering_sessions.filter(router=r.id)
debug(len(s))
debug(next(s).serialize())
```

### Expected Behavior

I would expect to get this output

```
test.py:9 <module>
    r.serialize(): {
        'id': 188,
        'display': 'bg1-ams1',
        'name': 'bg1-ams1',
        'hostname': 'ju1-lab1-mgmt',
        'platform': 2,
        'encrypt_passwords': True,
        'configuration_template': 1,
        'local_autonomous_system': 1130,
        'netbox_device_id': None,
        'device_state': 'enabled',
        'use_netbox': False,
        'config_context': None,
        'napalm_username': '',
        'napalm_password': None,
        'napalm_timeout': 0,
        'napalm_args': None,
        'comments': '',
        'tags': [],
    } (dict) len=18
test.py:11 <module>
    len(s): 921 (int)
test.py:13 <module>
    next(s).serialize(): {
        'id': 32,
        'display': 'private-peering - AS3292 - IP 128.76.59.12',
        'service_reference': None,
        'local_autonomous_system': 1130,
        'local_ip_address': None,
        'autonomous_system': 493,
        'bgp_group': 11,
        'relationship': 1,
        'ip_address': '128.76.59.12',
        'password': None,
        'encrypted_password': '',
        'multihop_ttl': 1,
        'enabled': True,
        'import_routing_policies': [],
        'export_routing_policies': [],
        'router': 188,
        'bgp_state': 'established',
        'received_prefix_count': 733,
        'advertised_prefix_count': 1,
        'last_established_state': '2021-11-13T11:34:20.286169-08:00',
        'comments': '',
        'tags': [],
    } (dict) len=22
```

### Observed Behavior

The logged request looks corect:

172.30.1.7 - - [07/Dec/2021:09:31:31 -0800] "GET /api/peering/direct-peering-sessions/?router=188&limit=0 HTTP"

But it fails with 

```
Traceback (most recent call last):
  File "/home/milton/pm/venv/lib/python3.8/site-packages/pynetbox/core/response.py", line 122, in __len__
    return self.request.count
AttributeError: 'Request' object has no attribute 'count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test.py", line 11, in <module>
    debug(len(s))
  File "/home/milton/pm/venv/lib/python3.8/site-packages/pynetbox/core/response.py", line 125, in __len__
    self._response_cache.append(next(self.response))
  File "/home/milton/pm/venv/lib/python3.8/site-packages/pynetbox/core/query.py", line 317, in get
    req = self._make_call(add_params=add_params)
  File "/home/milton/pm/venv/lib/python3.8/site-packages/pynetbox/core/query.py", line 284, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'router': ['Select a valid choice. 188 is not one of the available choices.']}
```

**Comment by mngan** [comment]
This is probably due to changes in `WritableNestedSerializer`, but I don't understand enough of that code to know what broke.

**Comment by mngan** [comment]
Found the new API docs which shows a new `router_id` query parameter that I should be using. Probably should update the API link in the Nav side bar to point at the new Swagger docs.

**Comment by gmazoyer** [comment]
Filtering has been rework in 1.4 and when using an ID to filter on a field you must always use the `_id` version of the field. In the case of filtering using a router if you use `router` it will try to filter on the router's hostname.
